services:
  - type: web
    name: efootball-auction-app
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production 