services:
  - type: web
    name: efootball-auction-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://efootball_auction_user:pXdd6FfpI9oRUoDoak5HKI8UJdtxcRMP@dpg-cvvltaadbo4c738a9hg0-a/efootball_auction
      - key: PYTHON_VERSION
        value: 3.11.0
    initialDeployHook: python init_db.py 