services:
  - type: web
    name: ssleague
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      echo "Checking for efootball_real.db file..."
      ls -la
      python init_db.py
    startCommand: gunicorn app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: efootball-auction-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 1
      - key: FLASK_APP
        value: app.py

databases:
  - name: efootball-auction-db
    plan: free
    databaseName: auction_db
    ipAllowList: [] 