services:
  - type: web
    name: efootball-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: efootball-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
    initialDeploy:
      - cp efootball_real.db /opt/render/project/src/ || echo "Database file not found, will create new database"
      - python init_migrations.py
      - python init_db.py

  - type: pserv
    name: efootball-db
    env: postgres
    plan: free
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: efootball 